language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH" 
  - composer global require "phpunit/phpunit=5.7.*"
  - composer install --no-interaction
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
